title: Eder Christian
author: Eder Christian
email: ederchristian92@gmail.com
description: >
  Passionate web developer, currently living in Sao Paulo, Brazil. I love to make things for the web and to put my effort on it.
baseurl: ""
url: "http://ederchristian.com"

twitter_username: ederchristian92
github_username:  ederchristian

minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
permalink: /:categories/:title
